version: 2
updates:
  # This section configures Dependabot to update npm dependencies.
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    commit-message:
      prefix: "[yarn]"
    assignees:
      - "dmytroidentitylabs"
    groups:
      dependencies:
        patterns:
          - "*"

  # This section configures Dependabot to update GitHub Actions dependencies.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "[github-actions]"
    assignees:
      - "dmytroidentitylabs"
    groups:
      dependencies:
        patterns:
          - "*"
