version: 2
updates:
  # This section configures Dependabot to update npm dependencies.
  - package-ecosystem: "npm"  # We're managing dependencies installed with npm. 
    target-branch: "main"  # Updates will be created on the "main" branch.
    directory: "/"  # Search for dependencies in the entire project.
    schedule:
      interval: "weekly"  # Check for updates every week.
    open-pull-requests-limit: 1  # Only create a maximum of 1 pull request at a time.
    versioning-strategy: increase  # Always update to the latest recommended version.
    commit-message:
      prefix: "[npm]"  # Pull request titles will start with "[npm]".
    assignees:
      - "olekid"  # Assign pull requests to "olekid".
    groups:
      dependencies:  # Group all dependency updates under "dependencies".
        patterns:  # Look for updates in any file or directory.
          - "*"  # Wildcard (*) matches everything.

  # This section configures Dependabot to update GitHub Actions dependencies.
  - package-ecosystem: "github-actions"  # We're managing workflow dependencies.
    directory: "/"  # Search for dependencies in the entire project (.github/workflows folder).
    schedule:
      interval: "weekly"  # Check for updates every week.
    open-pull-requests-limit: 1  # Only create a maximum of 1 pull request at a time.
    # versioning-strategy: increase Always update to the latest recommended version.
    commit-message:
      prefix: "[github-actions]"  # Pull request titles will start with "[github-actions]".
    assignees:
      - "DaniilIdentity"  # Assign pull requests to "DaniilIdentity".
    groups:
      dependencies:  # Group all dependency updates under "dependencies".
        patterns:  # Look for updates in any file or directory.
          - "*"  # Wildcard (*) matches everything.
